### PR TITLE
Added basic minions.

### PR DESCRIPTION
**Pull request by Si1kn**
Hello again. I have created basic minions with a really bad model. Minions work, the texture / model needs a rework and some pos issues, needs inventory ect. Thanks Si1kn

### CODE REVIEW

**Comment by Si1kn** [comment]
Conflicts fixed. Will create a recipe / craft in the next pull request and the only way to summon it is with the summon command. Thanks Si1kn again

**Comment by AlephInfinity1** [comment]
Sorry, was busy with school today so didn't see this until now.

Took a look at the code and they seem pretty good. The only problem I have is that I originally planned the minions to be tile entities rather than normal entities (since that'd make interactions much cleaner). Is it okay that I tweak the code a bit?

**Comment by AlephInfinity1** [comment]
On second thought, nah not really, entity minions are better for rendering purposes, and they work just as well.

**Comment by Si1kn** [comment]
Cool! This project is just for fun and I don't mind what you take / tweak, just having fun that's all.

**Pull request merged**
